[build]
  command = "bash ./build.sh && npm run build"
  functions = "netlify-functions/"
  environment = { PYTHON_VERSION = "3.8" }

[dev]
  command = "npm run start-api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
